### ISSUE TITLE
Define the BasicBuild standard v1.0

### ISSUE THREAD

**Issue by hainesm6** [LondonBiofoundry/basicsynbio#117]
- Need to define the types.
- Have a look at [Autoprotocol](https://autoprotocol.org/specification/)

**Comment by Benedict-Carling** [comment]
Hi @hainesm6 
I gave this a first go! you can check it out at [here](https://basicsynbio.web.app/basicbuild-standard)

**Comment by hainesm6** [comment]
Looking good @Benedict-Carling! Couple of questions which we can discuss later:
- Where is the source code located?
- We should have a link to this in the Python package reST documentation.

**Comment by Benedict-Carling** [comment]
Hi @hainesm6

The source code is for this page is at `basicsynbio_frontend/src/pages/BasicBuild.jsx` The code is quite long as I couldn't find a package to display the JSON in the way I wanted to, I had to do it with HTML/CSS

**Comment by Benedict-Carling** [comment]
Hi @hainesm6  the linker_class has now been updated to give options this was done in autoprotocol with Enum()
