### ISSUE TITLE
Remove "total clip reactions" from unique_parts and unique_linkers attribute of BasicBuild

### ISSUE THREAD

**Issue by hainesm6** [LondonBiofoundry/basicsynbio#122]
# Issue

This is ambiguous given total clip reactions can only be truely calculated if the physical assembly method is known. This is because purified clip reactions can be used in different numbers of assemblies depending on the assembly method.

# Solution

- [x] Remove this key-value pair from the serialised BasicBuild object.
- [x] Refresh documentation.
- [ ] Update the Open standard on the front end.

**Comment by hainesm6** [comment]
Hi @Benedict-Carling. I've done the first two tasks for this issue. Could you do the 3rd on the frontend by removing "total clip reactions", "total prefix clip reactions" and "total suffix clip reactions" from the open standard definition?

**Comment by Benedict-Carling** [comment]
Hey @hainesm6 I removed those fields from the frontend open standard definition, let me know if there's any more changes 👍 

https://basicsynbio.web.app/basicbuild-standard
