### ISSUE TITLE
Do the .gb files get migrated from pypi?

### ISSUE THREAD

**Issue by hainesm6** [LondonBiofoundry/basicsynbio#28]
Alexis suggests this is the case.

**Comment by hainesm6** [comment]
@Benedict-Carling I've been trying to upload the current `setup.py ` to testpypi but I'm having trouble getting the .gb files to install in site packages, similar to the original problem we had as outlined by this issue.

Do you remember what you did? I've tried using both a MANIFEST.in file and the `package_data` keyword in the setup.py file but still not working 😢

**Comment by Benedict-Carling** [comment]
Hi @hainesm6, i'll have another look at this now 👍

**Comment by Benedict-Carling** [comment]
Hi @hainesm6 , I had the same issue trying to upload to test pypi.

If I change the line shown in the image below, it allows the package data files to be read 👍 

![Screenshot 2021-01-12 at 10 24 18](https://user-images.githubusercontent.com/53439684/104302362-967a8d00-54c0-11eb-87e4-155072e30171.png)

**Comment by hainesm6** [comment]
Hmmm 🤔 

Is this the [address on testpypi](https://test.pypi.org/project/basicsynbiotesttesttest/) @Benedict-Carling ? I tried installing it as (below) but it still didn't have the .gb files.

```shell
$ pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple basicsynbiotesttesttest
``` 

Perhaps we can go through it together later on Teams?

**Comment by Benedict-Carling** [comment]
yep! although I think you might need, this version. I have quite a few version that aren't necessarily in order as they try different things, 0.1.7 is the latest one for me which worked.

pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple basicsynbiotesttesttest==0.1.7

**Comment by hainesm6** [comment]
I'm just in a meeting at the moment but will call you afterwards.

**Comment by hainesm6** [comment]
Something to do with how `setuptools.find_packages()` locates packages using the `where` argument. Getting rid of this solved the problem.

Worth posting this as an issue in the [setuptools repo](https://github.com/pypa/setuptools).

**Comment by hainesm6** [comment]
https://github.com/pypa/setuptools/issues/2546
